id: IB99C5856
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T20:30:50+00:00'
last_modified: '2022-06-08T10:51:08.433068+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17595
  title: ཀུན་རིག་གི་ཆོ་ག་གཞན་ཕན་མཐའ་ཡས་ཀྱི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A14A:
      image_group_id: I1KG17981
      title: ''
      total_pages: 288
      order: 1
      base_file: A14A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
